service: candle-computer

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${file(../parameters.yml):stage}
  region: ${file(../parameters.yml):region}
  memorySize: 128

  deploymentBucket:
    name: ${file(../parameters.yml):deploymentBucketName}

  tags:
    project: Kryptopus

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: "*"

functions:
  compute:
    name: ${self:provider.stage}-kryptopus-compute-candle
    handler: handler.compute
    environment:
      CANDLE_TABLE_NAME: ${file(../parameters.yml):candleTableName}
    timeout: 60

  compute-interval:
    name: ${self:provider.stage}-kryptopus-compute-interval-candles
    handler: handler.computeAll
    timeout: 300
    environment:
      SYMBOL_TABLE_NAME: ${file(../parameters.yml):symbolTableName}
      COMPUTE_FUNCTION_NAME: ${self:functions.compute.name}
    events:
      - schedule: 
          name: ${self:provider.stage}-kryptopus-compute-5m-candles
          description: Compute 5m candles
          rate: rate(5 minutes)
          input:
            sourceIntervalName: 1m
            sourceIntervalDuration: 60000
            targetIntervalName: 5m
            targetIntervalDuration: 300000




