service: binance-collector

provider:
  name: aws
  runtime: nodejs8.10

  stage: ${file(../parameters.yml):stage}
  region: ${file(../parameters.yml):region}
  memorySize: 128

  deploymentBucket:
    name: ${file(../parameters.yml):deploymentBucketName}

  tags:
    project: Kryptopus

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource: "*"

plugins:
  - serverless-dynamodb-autoscaling


functions:
  discover-symbols:
    name: ${self:provider.stage}-kryptopus-discover-binance-symbols
    handler: handler.discoverSymbols
    environment:
      SYMBOL_TABLE_NAME: ${file(../parameters.yml):symbolTableName}
    events:
      - schedule: 
          name: ${self:provider.stage}-kryptopus-discover-binance-symbols
          description: Discover Binance symbols every day
          rate: rate(1 day)
          enabled: true
    timeout: 300

