service: binance-collector

provider:
  name: aws
  runtime: nodejs8.10

  stage: dev
  region: eu-west-1
  memorySize: 128
  timeout: 60

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  collect-all:
    handler: handler.collectAll
    events:
      - schedule: rate(1 minute)

  collect:
    handler: handler.collect


